// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/auth/:provider/callback": {
    params: {
      "provider": string;
    };
  };
  "/auth/:provider": {
    params: {
      "provider": string;
    };
  };
  "/forgot-password": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/onboarding/:provider": {
    params: {
      "provider": string;
    };
  };
  "/reset-password": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/verify": {
    params: {};
  };
  "/webauthn/authentication": {
    params: {};
  };
  "/webauthn/registration": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/tos": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/admin/cache": {
    params: {};
  };
  "/admin/cache/lru/:cacheKey": {
    params: {
      "cacheKey": string;
    };
  };
  "/admin/cache/sqlite": {
    params: {};
  };
  "/admin/cache/sqlite/:cacheKey": {
    params: {
      "cacheKey": string;
    };
  };
  "/me": {
    params: {};
  };
  "/resources/download-user-data": {
    params: {};
  };
  "/resources/healthcheck": {
    params: {};
  };
  "/resources/images": {
    params: {};
  };
  "/resources/theme-switch": {
    params: {};
  };
  "/settings/profile": {
    params: {};
  };
  "/settings/profile/change-email": {
    params: {};
  };
  "/settings/profile/connections": {
    params: {};
  };
  "/settings/profile/passkeys": {
    params: {};
  };
  "/settings/profile/password": {
    params: {};
  };
  "/settings/profile/password/create": {
    params: {};
  };
  "/settings/profile/photo": {
    params: {};
  };
  "/settings/profile/two-factor": {
    params: {};
  };
  "/settings/profile/two-factor/disable": {
    params: {};
  };
  "/settings/profile/two-factor/verify": {
    params: {};
  };
  "/users/:username": {
    params: {
      "username": string;
    };
  };
  "/users/:username/articles": {
    params: {
      "username": string;
    };
  };
  "/users/:username/articles/:articleId": {
    params: {
      "username": string;
      "articleId": string;
    };
  };
  "/users/:username/articles/:articleId/edit": {
    params: {
      "username": string;
      "articleId": string;
    };
  };
  "/users/:username/articles/new": {
    params: {
      "username": string;
    };
  };
  "/users": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*" | "/auth/:provider/callback" | "/auth/:provider" | "/forgot-password" | "/login" | "/logout" | "/onboarding" | "/onboarding/:provider" | "/reset-password" | "/signup" | "/verify" | "/webauthn/authentication" | "/webauthn/registration" | "/about" | "/privacy" | "/support" | "/tos" | "/robots.txt" | "/sitemap.xml" | "/admin/cache" | "/admin/cache/lru/:cacheKey" | "/admin/cache/sqlite" | "/admin/cache/sqlite/:cacheKey" | "/me" | "/resources/download-user-data" | "/resources/healthcheck" | "/resources/images" | "/resources/theme-switch" | "/settings/profile" | "/settings/profile/change-email" | "/settings/profile/connections" | "/settings/profile/passkeys" | "/settings/profile/password" | "/settings/profile/password/create" | "/settings/profile/photo" | "/settings/profile/two-factor" | "/settings/profile/two-factor/disable" | "/settings/profile/two-factor/verify" | "/users/:username" | "/users/:username/articles" | "/users/:username/articles/:articleId" | "/users/:username/articles/:articleId/edit" | "/users/:username/articles/new" | "/users";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
  "routes/_auth+/auth.$provider.callback.ts": {
    id: "routes/_auth+/auth.$provider.callback";
    page: "/auth/:provider/callback";
  };
  "routes/_auth+/auth_.$provider.ts": {
    id: "routes/_auth+/auth_.$provider";
    page: "/auth/:provider";
  };
  "routes/_auth+/forgot-password.tsx": {
    id: "routes/_auth+/forgot-password";
    page: "/forgot-password";
  };
  "routes/_auth+/login.tsx": {
    id: "routes/_auth+/login";
    page: "/login";
  };
  "routes/_auth+/logout.tsx": {
    id: "routes/_auth+/logout";
    page: "/logout";
  };
  "routes/_auth+/onboarding.tsx": {
    id: "routes/_auth+/onboarding";
    page: "/onboarding";
  };
  "routes/_auth+/onboarding_.$provider.tsx": {
    id: "routes/_auth+/onboarding_.$provider";
    page: "/onboarding/:provider";
  };
  "routes/_auth+/reset-password.tsx": {
    id: "routes/_auth+/reset-password";
    page: "/reset-password";
  };
  "routes/_auth+/signup.tsx": {
    id: "routes/_auth+/signup";
    page: "/signup";
  };
  "routes/_auth+/verify.tsx": {
    id: "routes/_auth+/verify";
    page: "/verify";
  };
  "routes/_auth+/webauthn+/authentication.ts": {
    id: "routes/_auth+/webauthn+/authentication";
    page: "/webauthn/authentication";
  };
  "routes/_auth+/webauthn+/registration.ts": {
    id: "routes/_auth+/webauthn+/registration";
    page: "/webauthn/registration";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/_marketing+/about.tsx": {
    id: "routes/_marketing+/about";
    page: "/about";
  };
  "routes/_marketing+/index.tsx": {
    id: "routes/_marketing+/index";
    page: "/";
  };
  "routes/_marketing+/privacy.tsx": {
    id: "routes/_marketing+/privacy";
    page: "/privacy";
  };
  "routes/_marketing+/support.tsx": {
    id: "routes/_marketing+/support";
    page: "/support";
  };
  "routes/_marketing+/tos.tsx": {
    id: "routes/_marketing+/tos";
    page: "/tos";
  };
  "routes/_seo+/robots[.]txt.ts": {
    id: "routes/_seo+/robots[.]txt";
    page: "/robots.txt";
  };
  "routes/_seo+/sitemap[.]xml.ts": {
    id: "routes/_seo+/sitemap[.]xml";
    page: "/sitemap.xml";
  };
  "routes/admin+/cache.tsx": {
    id: "routes/admin+/cache";
    page: "/admin/cache";
  };
  "routes/admin+/cache_.lru.$cacheKey.ts": {
    id: "routes/admin+/cache_.lru.$cacheKey";
    page: "/admin/cache/lru/:cacheKey";
  };
  "routes/admin+/cache_.sqlite.tsx": {
    id: "routes/admin+/cache_.sqlite";
    page: "/admin/cache/sqlite" | "/admin/cache/sqlite/:cacheKey";
  };
  "routes/admin+/cache_.sqlite.$cacheKey.ts": {
    id: "routes/admin+/cache_.sqlite.$cacheKey";
    page: "/admin/cache/sqlite/:cacheKey";
  };
  "routes/me.tsx": {
    id: "routes/me";
    page: "/me";
  };
  "routes/resources+/download-user-data.tsx": {
    id: "routes/resources+/download-user-data";
    page: "/resources/download-user-data";
  };
  "routes/resources+/healthcheck.tsx": {
    id: "routes/resources+/healthcheck";
    page: "/resources/healthcheck";
  };
  "routes/resources+/images.tsx": {
    id: "routes/resources+/images";
    page: "/resources/images";
  };
  "routes/resources+/theme-switch.tsx": {
    id: "routes/resources+/theme-switch";
    page: "/resources/theme-switch";
  };
  "routes/settings+/profile.tsx": {
    id: "routes/settings+/profile";
    page: "/settings/profile" | "/settings/profile/change-email" | "/settings/profile/connections" | "/settings/profile/passkeys" | "/settings/profile/password" | "/settings/profile/password/create" | "/settings/profile/photo" | "/settings/profile/two-factor" | "/settings/profile/two-factor/disable" | "/settings/profile/two-factor/verify";
  };
  "routes/settings+/profile.change-email.tsx": {
    id: "routes/settings+/profile.change-email";
    page: "/settings/profile/change-email";
  };
  "routes/settings+/profile.connections.tsx": {
    id: "routes/settings+/profile.connections";
    page: "/settings/profile/connections";
  };
  "routes/settings+/profile.index.tsx": {
    id: "routes/settings+/profile.index";
    page: "/settings/profile";
  };
  "routes/settings+/profile.passkeys.tsx": {
    id: "routes/settings+/profile.passkeys";
    page: "/settings/profile/passkeys";
  };
  "routes/settings+/profile.password.tsx": {
    id: "routes/settings+/profile.password";
    page: "/settings/profile/password";
  };
  "routes/settings+/profile.password_.create.tsx": {
    id: "routes/settings+/profile.password_.create";
    page: "/settings/profile/password/create";
  };
  "routes/settings+/profile.photo.tsx": {
    id: "routes/settings+/profile.photo";
    page: "/settings/profile/photo";
  };
  "routes/settings+/profile.two-factor.tsx": {
    id: "routes/settings+/profile.two-factor";
    page: "/settings/profile/two-factor" | "/settings/profile/two-factor/disable" | "/settings/profile/two-factor/verify";
  };
  "routes/settings+/profile.two-factor.disable.tsx": {
    id: "routes/settings+/profile.two-factor.disable";
    page: "/settings/profile/two-factor/disable";
  };
  "routes/settings+/profile.two-factor.index.tsx": {
    id: "routes/settings+/profile.two-factor.index";
    page: "/settings/profile/two-factor";
  };
  "routes/settings+/profile.two-factor.verify.tsx": {
    id: "routes/settings+/profile.two-factor.verify";
    page: "/settings/profile/two-factor/verify";
  };
  "routes/users+/$username.tsx": {
    id: "routes/users+/$username";
    page: "/users/:username";
  };
  "routes/users+/$username_+/articles.tsx": {
    id: "routes/users+/$username_+/articles";
    page: "/users/:username/articles" | "/users/:username/articles/:articleId" | "/users/:username/articles/:articleId/edit" | "/users/:username/articles/new";
  };
  "routes/users+/$username_+/articles.$articleId.tsx": {
    id: "routes/users+/$username_+/articles.$articleId";
    page: "/users/:username/articles/:articleId";
  };
  "routes/users+/$username_+/articles.$articleId_.edit.tsx": {
    id: "routes/users+/$username_+/articles.$articleId_.edit";
    page: "/users/:username/articles/:articleId/edit";
  };
  "routes/users+/$username_+/articles.index.tsx": {
    id: "routes/users+/$username_+/articles.index";
    page: "/users/:username/articles";
  };
  "routes/users+/$username_+/articles.new.tsx": {
    id: "routes/users+/$username_+/articles.new";
    page: "/users/:username/articles/new";
  };
  "routes/users+/index.tsx": {
    id: "routes/users+/index";
    page: "/users";
  };
};